---
- hosts: localhost
  vars:
    ovirt_host_domain: {{ ansible_domain }}
    ovirt_host_fqdn: {{ ansible_nodename }}
    ovirt_host_ip: {{ ansible_default_ipv4.address }}
  vars_prompt:
  - name: "ovirt_engine_admin_password"
    prompt: "Please enter a password for admin@internal (ovirt engine admin)"
  remote_user: root
  roles:
  - centos7-ovirt4-prereqs
  - centos7-ansible23
