---
- name: install ovirt release41 repo (latest)
  yum:
    name: http://resources.ovirt.org/pub/yum-repo/ovirt-release41.rpm
    state: installed
- name: install updates
  yum:
    name: '*'
    state: latest
- name: switch to Permissive until I figure out what goes wrong when Enforcing
  selinux:
    policy: targeted
    state: permissive
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile: 
    backrefs: yes
    dest: /etc/ssh/sshd_config
    regexp: 'Ciphers(.*)$'
    line: '#Ciphers\1'
  notify: 'restart sshd'
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile:
    backrefs: yes
    dest: /etc/ssh/sshd_config
    regexp: 'MACs(.*)$'
    line: '#MACs\1'
  notify: 'restart sshd'
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile:
    backrefs: yes
    dest: /etc/ssh/sshd_config
    regexp: 'KexAlgorithms(.*)$'
    line: '#KexAlgorithms\1'
  notify: 'restart sshd'
- name: Create storage share mountpoint
  file: 
    path=/share/storage
    state=directory
- name: create lv for share
  lvol:
    vg: '{{ vg_name }}'
    lv: lv_share_storage
    size: 50G
- name: mkfs lv_share_storage
  filesystem:
    fstype: xfs
    dev: '/dev/{{ vg_name }}/lv_share_storage'
- name: mount new FS
  mount: 
    name: /share/storage
    src: '/dev/{{ vg_name }}/lv_share_storage'
    fstype: xfs
    state: mounted
- name: Change share owner
  file: 
    path: '/share/storage'
    owner: 36
    group: 36
- name: Install ovirt-engine
  yum: name=ovirt-engine
